services:
  db:
    image: postgres:18-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: SMJLT:co6x3HU0r)
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 256m
    command: >
      postgres
        -c shared_buffers=128MB
        -c work_mem=4MB
        -c maintenance_work_mem=64MB
        -c max_connections=50

volumes:
  postgres_data:
